python mysql_to_sqlite_bulk_advanced.py --table schema_migrations
python mysql_to_sqlite_bulk_advanced.py --table sys_content_info_grids
python mysql_to_sqlite_bulk_advanced.py --table sys_form_display_inputs
python mysql_to_sqlite_bulk_advanced.py --table sys_form_displays
python mysql_to_sqlite_bulk_advanced.py --table sys_form_inputs
python mysql_to_sqlite_bulk_advanced.py --table sys_grid_actions
python mysql_to_sqlite_bulk_advanced.py --table sys_grid_fields
python mysql_to_sqlite_bulk_advanced.py --table sys_menu_items
python mysql_to_sqlite_bulk_advanced.py --table sys_menu_sets
python mysql_to_sqlite_bulk_advanced.py --table sys_menu_templates
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_content_info
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_form
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_grid
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_menu
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_page
python mysql_to_sqlite_bulk_advanced.py --table sys_objects_view
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_blocks
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_blocks_data
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_content_placeholders
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_layouts
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_types
python mysql_to_sqlite_bulk_advanced.py --table sys_pages_wiki_blocks
python mysql_to_sqlite_bulk_advanced.py --table sys_permalinks
python mysql_to_sqlite_bulk_advanced.py --table sys_rewrite_rules
python mysql_to_sqlite_bulk_advanced.py --table sys_seo_links
python mysql_to_sqlite_bulk_advanced.py --table sys_seo_uri_rewrites
python mysql_to_sqlite_bulk_advanced.py --table sys_std_pages
python mysql_to_sqlite_bulk_advanced.py --table sys_std_pages_widgets
python mysql_to_sqlite_bulk_advanced.py --table sys_std_widgets
python mysql_to_sqlite_bulk_advanced.py --table sys_std_widgets_bookmarks