defmodule DeeperHub.WebInterface.Router do
  @moduledoc """
  Roteador principal para a API REST do DeeperHub.
  Este módulo define as rotas e recursos disponíveis na API.
  """
  use Plug.Router
  use Plug.ErrorHandler

  # Plugs de depuração
  plug(Plug.Logger, log: :debug)

  # Parsers para formatos diferentes
  plug(Plug.Parsers,
    parsers: [:json],
    pass: ["application/json"],
    json_decoder: Jason
  )

  # Pipeline principal
  plug(:match)
  plug(:dispatch)

  # API Routes
  forward("/api/bx_persons_cmts", to: DeeperHub.WebInterface.Resources.BxPersonsCmtsResource)
  forward("/api/bx_persons_cmts_notes", to: DeeperHub.WebInterface.Resources.BxPersonsCmtsNotesResource)
  forward("/api/bx_persons_data", to: DeeperHub.WebInterface.Resources.BxPersonsDataResource)
  forward("/api/bx_persons_favorites_track", to: DeeperHub.WebInterface.Resources.BxPersonsFavoritesTrackResource)
  forward("/api/bx_persons_meta_keywords", to: DeeperHub.WebInterface.Resources.BxPersonsMetaKeywordsResource)
  forward("/api/bx_persons_meta_locations", to: DeeperHub.WebInterface.Resources.BxPersonsMetaLocationsResource)
  forward("/api/bx_persons_meta_mentions", to: DeeperHub.WebInterface.Resources.BxPersonsMetaMentionsResource)
  forward("/api/bx_persons_pictures", to: DeeperHub.WebInterface.Resources.BxPersonsPicturesResource)
  forward("/api/bx_persons_pictures_resized", to: DeeperHub.WebInterface.Resources.BxPersonsPicturesResizedResource)
  forward("/api/bx_persons_reactions", to: DeeperHub.WebInterface.Resources.BxPersonsReactionsResource)
  forward("/api/bx_persons_reactions_track", to: DeeperHub.WebInterface.Resources.BxPersonsReactionsTrackResource)
  forward("/api/bx_persons_reports", to: DeeperHub.WebInterface.Resources.BxPersonsReportsResource)
  forward("/api/bx_persons_reports_track", to: DeeperHub.WebInterface.Resources.BxPersonsReportsTrackResource)
  forward("/api/bx_persons_scores", to: DeeperHub.WebInterface.Resources.BxPersonsScoresResource)
  forward("/api/bx_persons_scores_track", to: DeeperHub.WebInterface.Resources.BxPersonsScoresTrackResource)
  forward("/api/bx_persons_skills", to: DeeperHub.WebInterface.Resources.BxPersonsSkillsResource)
  forward("/api/bx_persons_views_track", to: DeeperHub.WebInterface.Resources.BxPersonsViewsTrackResource)
  forward("/api/bx_persons_votes", to: DeeperHub.WebInterface.Resources.BxPersonsVotesResource)
  forward("/api/bx_persons_votes_track", to: DeeperHub.WebInterface.Resources.BxPersonsVotesTrackResource)
  forward("/api/sys_accounts", to: DeeperHub.WebInterface.Resources.SysAccountsResource)
  forward("/api/sys_accounts_password", to: DeeperHub.WebInterface.Resources.SysAccountsPasswordResource)
  forward("/api/sys_accounts_pictures", to: DeeperHub.WebInterface.Resources.SysAccountsPicturesResource)
  forward("/api/sys_accounts_pictures_resized", to: DeeperHub.WebInterface.Resources.SysAccountsPicturesResizedResource)
  forward("/api/sys_acl_actions", to: DeeperHub.WebInterface.Resources.SysAclActionsResource)
  forward("/api/sys_acl_actions_track", to: DeeperHub.WebInterface.Resources.SysAclActionsTrackResource)
  forward("/api/sys_acl_levels", to: DeeperHub.WebInterface.Resources.SysAclLevelsResource)
  forward("/api/sys_acl_levels_members", to: DeeperHub.WebInterface.Resources.SysAclLevelsMembersResource)
  forward("/api/sys_acl_matrix", to: DeeperHub.WebInterface.Resources.SysAclMatrixResource)
  forward("/api/sys_agents_assistants", to: DeeperHub.WebInterface.Resources.SysAgentsAssistantsResource)
  forward("/api/sys_agents_assistants_chats", to: DeeperHub.WebInterface.Resources.SysAgentsAssistantsChatsResource)
  forward("/api/sys_agents_assistants_chats_files", to: DeeperHub.WebInterface.Resources.SysAgentsAssistantsChatsFilesResource)
  forward("/api/sys_agents_assistants_chats_messages", to: DeeperHub.WebInterface.Resources.SysAgentsAssistantsChatsMessagesResource)
  forward("/api/sys_agents_assistants_files", to: DeeperHub.WebInterface.Resources.SysAgentsAssistantsFilesResource)
  forward("/api/sys_agents_automators", to: DeeperHub.WebInterface.Resources.SysAgentsAutomatorsResource)
  forward("/api/sys_agents_automators_assistants", to: DeeperHub.WebInterface.Resources.SysAgentsAutomatorsAssistantsResource)
  forward("/api/sys_agents_automators_helpers", to: DeeperHub.WebInterface.Resources.SysAgentsAutomatorsHelpersResource)
  forward("/api/sys_agents_automators_messages", to: DeeperHub.WebInterface.Resources.SysAgentsAutomatorsMessagesResource)
  forward("/api/sys_agents_automators_providers", to: DeeperHub.WebInterface.Resources.SysAgentsAutomatorsProvidersResource)
  forward("/api/sys_agents_helpers", to: DeeperHub.WebInterface.Resources.SysAgentsHelpersResource)
  forward("/api/sys_agents_models", to: DeeperHub.WebInterface.Resources.SysAgentsModelsResource)
  forward("/api/sys_agents_provider_options", to: DeeperHub.WebInterface.Resources.SysAgentsProviderOptionsResource)
  forward("/api/sys_agents_provider_types", to: DeeperHub.WebInterface.Resources.SysAgentsProviderTypesResource)
  forward("/api/sys_agents_providers", to: DeeperHub.WebInterface.Resources.SysAgentsProvidersResource)
  forward("/api/sys_agents_providers_values", to: DeeperHub.WebInterface.Resources.SysAgentsProvidersValuesResource)
  forward("/api/sys_alerts", to: DeeperHub.WebInterface.Resources.SysAlertsResource)
  forward("/api/sys_alerts_cache_triggers", to: DeeperHub.WebInterface.Resources.SysAlertsCacheTriggersResource)
  forward("/api/sys_alerts_handlers", to: DeeperHub.WebInterface.Resources.SysAlertsHandlersResource)
  forward("/api/sys_api_keys", to: DeeperHub.WebInterface.Resources.SysApiKeysResource)
  forward("/api/sys_api_origins", to: DeeperHub.WebInterface.Resources.SysApiOriginsResource)
  forward("/api/sys_audit", to: DeeperHub.WebInterface.Resources.SysAuditResource)
  forward("/api/sys_background_jobs", to: DeeperHub.WebInterface.Resources.SysBackgroundJobsResource)
  forward("/api/sys_badges", to: DeeperHub.WebInterface.Resources.SysBadgesResource)
  forward("/api/sys_badges2objects", to: DeeperHub.WebInterface.Resources.SysBadges2objectsResource)
  forward("/api/sys_categories", to: DeeperHub.WebInterface.Resources.SysCategoriesResource)
  forward("/api/sys_categories2objects", to: DeeperHub.WebInterface.Resources.SysCategories2objectsResource)
  forward("/api/sys_cmts_ids", to: DeeperHub.WebInterface.Resources.SysCmtsIdsResource)
  forward("/api/sys_cmts_images", to: DeeperHub.WebInterface.Resources.SysCmtsImagesResource)
  forward("/api/sys_cmts_images2entries", to: DeeperHub.WebInterface.Resources.SysCmtsImages2entriesResource)
  forward("/api/sys_cmts_images_preview", to: DeeperHub.WebInterface.Resources.SysCmtsImagesPreviewResource)
  forward("/api/sys_cmts_meta_keywords", to: DeeperHub.WebInterface.Resources.SysCmtsMetaKeywordsResource)
  forward("/api/sys_cmts_meta_mentions", to: DeeperHub.WebInterface.Resources.SysCmtsMetaMentionsResource)
  forward("/api/sys_cmts_reactions", to: DeeperHub.WebInterface.Resources.SysCmtsReactionsResource)
  forward("/api/sys_cmts_reactions_track", to: DeeperHub.WebInterface.Resources.SysCmtsReactionsTrackResource)
  forward("/api/sys_cmts_reports", to: DeeperHub.WebInterface.Resources.SysCmtsReportsResource)
  forward("/api/sys_cmts_reports_track", to: DeeperHub.WebInterface.Resources.SysCmtsReportsTrackResource)
  forward("/api/sys_cmts_scores", to: DeeperHub.WebInterface.Resources.SysCmtsScoresResource)
  forward("/api/sys_cmts_scores_track", to: DeeperHub.WebInterface.Resources.SysCmtsScoresTrackResource)
  forward("/api/sys_cmts_votes", to: DeeperHub.WebInterface.Resources.SysCmtsVotesResource)
  forward("/api/sys_cmts_votes_track", to: DeeperHub.WebInterface.Resources.SysCmtsVotesTrackResource)
  forward("/api/sys_content_info_grids", to: DeeperHub.WebInterface.Resources.SysContentInfoGridsResource)
  forward("/api/sys_cron_jobs", to: DeeperHub.WebInterface.Resources.SysCronJobsResource)
  forward("/api/sys_email_templates", to: DeeperHub.WebInterface.Resources.SysEmailTemplatesResource)
  forward("/api/sys_embeded_data", to: DeeperHub.WebInterface.Resources.SysEmbededDataResource)
  forward("/api/sys_files", to: DeeperHub.WebInterface.Resources.SysFilesResource)
  forward("/api/sys_form_display_inputs", to: DeeperHub.WebInterface.Resources.SysFormDisplayInputsResource)
  forward("/api/sys_form_displays", to: DeeperHub.WebInterface.Resources.SysFormDisplaysResource)
  forward("/api/sys_form_fields_ids", to: DeeperHub.WebInterface.Resources.SysFormFieldsIdsResource)
  forward("/api/sys_form_fields_reaction", to: DeeperHub.WebInterface.Resources.SysFormFieldsReactionResource)
  forward("/api/sys_form_fields_reaction_track", to: DeeperHub.WebInterface.Resources.SysFormFieldsReactionTrackResource)
  forward("/api/sys_form_fields_votes", to: DeeperHub.WebInterface.Resources.SysFormFieldsVotesResource)
  forward("/api/sys_form_fields_votes_track", to: DeeperHub.WebInterface.Resources.SysFormFieldsVotesTrackResource)
  forward("/api/sys_form_inputs", to: DeeperHub.WebInterface.Resources.SysFormInputsResource)
  forward("/api/sys_form_inputs_privacy", to: DeeperHub.WebInterface.Resources.SysFormInputsPrivacyResource)
  forward("/api/sys_form_pre_lists", to: DeeperHub.WebInterface.Resources.SysFormPreListsResource)
  forward("/api/sys_form_pre_values", to: DeeperHub.WebInterface.Resources.SysFormPreValuesResource)
  forward("/api/sys_grid_actions", to: DeeperHub.WebInterface.Resources.SysGridActionsResource)
  forward("/api/sys_grid_fields", to: DeeperHub.WebInterface.Resources.SysGridFieldsResource)
  forward("/api/sys_iframely_data", to: DeeperHub.WebInterface.Resources.SysIframelyDataResource)
  forward("/api/sys_images", to: DeeperHub.WebInterface.Resources.SysImagesResource)
  forward("/api/sys_images_custom", to: DeeperHub.WebInterface.Resources.SysImagesCustomResource)
  forward("/api/sys_images_editor", to: DeeperHub.WebInterface.Resources.SysImagesEditorResource)
  forward("/api/sys_images_editor_resized", to: DeeperHub.WebInterface.Resources.SysImagesEditorResizedResource)
  forward("/api/sys_images_resized", to: DeeperHub.WebInterface.Resources.SysImagesResizedResource)
  forward("/api/sys_injections", to: DeeperHub.WebInterface.Resources.SysInjectionsResource)
  forward("/api/sys_injections_admin", to: DeeperHub.WebInterface.Resources.SysInjectionsAdminResource)
  forward("/api/sys_keys", to: DeeperHub.WebInterface.Resources.SysKeysResource)
  forward("/api/sys_labels", to: DeeperHub.WebInterface.Resources.SysLabelsResource)
  forward("/api/sys_localization_categories", to: DeeperHub.WebInterface.Resources.SysLocalizationCategoriesResource)
  forward("/api/sys_localization_keys", to: DeeperHub.WebInterface.Resources.SysLocalizationKeysResource)
  forward("/api/sys_localization_languages", to: DeeperHub.WebInterface.Resources.SysLocalizationLanguagesResource)
  forward("/api/sys_localization_strings", to: DeeperHub.WebInterface.Resources.SysLocalizationStringsResource)
  forward("/api/sys_menu_items", to: DeeperHub.WebInterface.Resources.SysMenuItemsResource)
  forward("/api/sys_menu_sets", to: DeeperHub.WebInterface.Resources.SysMenuSetsResource)
  forward("/api/sys_menu_templates", to: DeeperHub.WebInterface.Resources.SysMenuTemplatesResource)
  forward("/api/sys_modules", to: DeeperHub.WebInterface.Resources.SysModulesResource)
  forward("/api/sys_modules_file_tracks", to: DeeperHub.WebInterface.Resources.SysModulesFileTracksResource)
  forward("/api/sys_modules_relations", to: DeeperHub.WebInterface.Resources.SysModulesRelationsResource)
  forward("/api/sys_objects_auths", to: DeeperHub.WebInterface.Resources.SysObjectsAuthsResource)
  forward("/api/sys_objects_captcha", to: DeeperHub.WebInterface.Resources.SysObjectsCaptchaResource)
  forward("/api/sys_objects_category", to: DeeperHub.WebInterface.Resources.SysObjectsCategoryResource)
  forward("/api/sys_objects_chart", to: DeeperHub.WebInterface.Resources.SysObjectsChartResource)
  forward("/api/sys_objects_cmts", to: DeeperHub.WebInterface.Resources.SysObjectsCmtsResource)
  forward("/api/sys_objects_connection", to: DeeperHub.WebInterface.Resources.SysObjectsConnectionResource)
  forward("/api/sys_objects_content_info", to: DeeperHub.WebInterface.Resources.SysObjectsContentInfoResource)
  forward("/api/sys_objects_editor", to: DeeperHub.WebInterface.Resources.SysObjectsEditorResource)
  forward("/api/sys_objects_embeds", to: DeeperHub.WebInterface.Resources.SysObjectsEmbedsResource)
  forward("/api/sys_objects_favorite", to: DeeperHub.WebInterface.Resources.SysObjectsFavoriteResource)
  forward("/api/sys_objects_feature", to: DeeperHub.WebInterface.Resources.SysObjectsFeatureResource)
  forward("/api/sys_objects_file_handlers", to: DeeperHub.WebInterface.Resources.SysObjectsFileHandlersResource)
  forward("/api/sys_objects_form", to: DeeperHub.WebInterface.Resources.SysObjectsFormResource)
  forward("/api/sys_objects_grid", to: DeeperHub.WebInterface.Resources.SysObjectsGridResource)
  forward("/api/sys_objects_live_updates", to: DeeperHub.WebInterface.Resources.SysObjectsLiveUpdatesResource)
  forward("/api/sys_objects_location_field", to: DeeperHub.WebInterface.Resources.SysObjectsLocationFieldResource)
  forward("/api/sys_objects_location_map", to: DeeperHub.WebInterface.Resources.SysObjectsLocationMapResource)
  forward("/api/sys_objects_logs", to: DeeperHub.WebInterface.Resources.SysObjectsLogsResource)
  forward("/api/sys_objects_menu", to: DeeperHub.WebInterface.Resources.SysObjectsMenuResource)
  forward("/api/sys_objects_metatags", to: DeeperHub.WebInterface.Resources.SysObjectsMetatagsResource)
  forward("/api/sys_objects_page", to: DeeperHub.WebInterface.Resources.SysObjectsPageResource)
  forward("/api/sys_objects_payments", to: DeeperHub.WebInterface.Resources.SysObjectsPaymentsResource)
  forward("/api/sys_objects_player", to: DeeperHub.WebInterface.Resources.SysObjectsPlayerResource)
  forward("/api/sys_objects_privacy", to: DeeperHub.WebInterface.Resources.SysObjectsPrivacyResource)
  forward("/api/sys_objects_push", to: DeeperHub.WebInterface.Resources.SysObjectsPushResource)
  forward("/api/sys_objects_recommendation", to: DeeperHub.WebInterface.Resources.SysObjectsRecommendationResource)
  forward("/api/sys_objects_report", to: DeeperHub.WebInterface.Resources.SysObjectsReportResource)
  forward("/api/sys_objects_rss", to: DeeperHub.WebInterface.Resources.SysObjectsRssResource)
  forward("/api/sys_objects_score", to: DeeperHub.WebInterface.Resources.SysObjectsScoreResource)
  forward("/api/sys_objects_search", to: DeeperHub.WebInterface.Resources.SysObjectsSearchResource)
  forward("/api/sys_objects_search_extended", to: DeeperHub.WebInterface.Resources.SysObjectsSearchExtendedResource)
  forward("/api/sys_objects_sms", to: DeeperHub.WebInterface.Resources.SysObjectsSmsResource)
  forward("/api/sys_objects_storage", to: DeeperHub.WebInterface.Resources.SysObjectsStorageResource)
  forward("/api/sys_objects_transcoder", to: DeeperHub.WebInterface.Resources.SysObjectsTranscoderResource)
  forward("/api/sys_objects_uploader", to: DeeperHub.WebInterface.Resources.SysObjectsUploaderResource)
  forward("/api/sys_objects_view", to: DeeperHub.WebInterface.Resources.SysObjectsViewResource)
  forward("/api/sys_objects_vote", to: DeeperHub.WebInterface.Resources.SysObjectsVoteResource)
  forward("/api/sys_objects_wiki", to: DeeperHub.WebInterface.Resources.SysObjectsWikiResource)
  forward("/api/sys_options", to: DeeperHub.WebInterface.Resources.SysOptionsResource)
  forward("/api/sys_options_categories", to: DeeperHub.WebInterface.Resources.SysOptionsCategoriesResource)
  forward("/api/sys_options_mixes", to: DeeperHub.WebInterface.Resources.SysOptionsMixesResource)
  forward("/api/sys_options_mixes2options", to: DeeperHub.WebInterface.Resources.SysOptionsMixes2optionsResource)
  forward("/api/sys_options_types", to: DeeperHub.WebInterface.Resources.SysOptionsTypesResource)
  forward("/api/sys_pages_blocks", to: DeeperHub.WebInterface.Resources.SysPagesBlocksResource)
  forward("/api/sys_pages_blocks_data", to: DeeperHub.WebInterface.Resources.SysPagesBlocksDataResource)
  forward("/api/sys_pages_content_placeholders", to: DeeperHub.WebInterface.Resources.SysPagesContentPlaceholdersResource)
  forward("/api/sys_pages_design_boxes", to: DeeperHub.WebInterface.Resources.SysPagesDesignBoxesResource)
  forward("/api/sys_pages_layouts", to: DeeperHub.WebInterface.Resources.SysPagesLayoutsResource)
  forward("/api/sys_pages_types", to: DeeperHub.WebInterface.Resources.SysPagesTypesResource)
  forward("/api/sys_pages_wiki_blocks", to: DeeperHub.WebInterface.Resources.SysPagesWikiBlocksResource)
  forward("/api/sys_permalinks", to: DeeperHub.WebInterface.Resources.SysPermalinksResource)
  forward("/api/sys_preloader", to: DeeperHub.WebInterface.Resources.SysPreloaderResource)
  forward("/api/sys_privacy_defaults", to: DeeperHub.WebInterface.Resources.SysPrivacyDefaultsResource)
  forward("/api/sys_privacy_groups", to: DeeperHub.WebInterface.Resources.SysPrivacyGroupsResource)
  forward("/api/sys_privacy_groups_custom", to: DeeperHub.WebInterface.Resources.SysPrivacyGroupsCustomResource)
  forward("/api/sys_privacy_groups_custom_members", to: DeeperHub.WebInterface.Resources.SysPrivacyGroupsCustomMembersResource)
  forward("/api/sys_privacy_groups_custom_memberships", to: DeeperHub.WebInterface.Resources.SysPrivacyGroupsCustomMembershipsResource)
  forward("/api/sys_profiles", to: DeeperHub.WebInterface.Resources.SysProfilesResource)
  forward("/api/sys_profiles_conn_bans", to: DeeperHub.WebInterface.Resources.SysProfilesConnBansResource)
  forward("/api/sys_profiles_conn_friends", to: DeeperHub.WebInterface.Resources.SysProfilesConnFriendsResource)
  forward("/api/sys_profiles_conn_relations", to: DeeperHub.WebInterface.Resources.SysProfilesConnRelationsResource)
  forward("/api/sys_profiles_conn_subscriptions", to: DeeperHub.WebInterface.Resources.SysProfilesConnSubscriptionsResource)
  forward("/api/sys_profiles_track", to: DeeperHub.WebInterface.Resources.SysProfilesTrackResource)
  forward("/api/sys_queue_email", to: DeeperHub.WebInterface.Resources.SysQueueEmailResource)
  forward("/api/sys_queue_push", to: DeeperHub.WebInterface.Resources.SysQueuePushResource)
  forward("/api/sys_recommendation_criteria", to: DeeperHub.WebInterface.Resources.SysRecommendationCriteriaResource)
  forward("/api/sys_recommendation_data", to: DeeperHub.WebInterface.Resources.SysRecommendationDataResource)
  forward("/api/sys_rewrite_rules", to: DeeperHub.WebInterface.Resources.SysRewriteRulesResource)
  forward("/api/sys_search_extended_fields", to: DeeperHub.WebInterface.Resources.SysSearchExtendedFieldsResource)
  forward("/api/sys_search_extended_sorting_fields", to: DeeperHub.WebInterface.Resources.SysSearchExtendedSortingFieldsResource)
  forward("/api/sys_seo_links", to: DeeperHub.WebInterface.Resources.SysSeoLinksResource)
  forward("/api/sys_seo_uri_rewrites", to: DeeperHub.WebInterface.Resources.SysSeoUriRewritesResource)
  forward("/api/sys_sessions", to: DeeperHub.WebInterface.Resources.SysSessionsResource)
  forward("/api/sys_statistics", to: DeeperHub.WebInterface.Resources.SysStatisticsResource)
  forward("/api/sys_std_pages", to: DeeperHub.WebInterface.Resources.SysStdPagesResource)
  forward("/api/sys_std_pages_widgets", to: DeeperHub.WebInterface.Resources.SysStdPagesWidgetsResource)
  forward("/api/sys_std_roles", to: DeeperHub.WebInterface.Resources.SysStdRolesResource)
  forward("/api/sys_std_roles_actions", to: DeeperHub.WebInterface.Resources.SysStdRolesActionsResource)
  forward("/api/sys_std_roles_actions2roles", to: DeeperHub.WebInterface.Resources.SysStdRolesActions2rolesResource)
  forward("/api/sys_std_roles_members", to: DeeperHub.WebInterface.Resources.SysStdRolesMembersResource)
  forward("/api/sys_std_widgets", to: DeeperHub.WebInterface.Resources.SysStdWidgetsResource)
  forward("/api/sys_std_widgets_bookmarks", to: DeeperHub.WebInterface.Resources.SysStdWidgetsBookmarksResource)
  forward("/api/sys_storage_deletions", to: DeeperHub.WebInterface.Resources.SysStorageDeletionsResource)
  forward("/api/sys_storage_ghosts", to: DeeperHub.WebInterface.Resources.SysStorageGhostsResource)
  forward("/api/sys_storage_mime_types", to: DeeperHub.WebInterface.Resources.SysStorageMimeTypesResource)
  forward("/api/sys_storage_tokens", to: DeeperHub.WebInterface.Resources.SysStorageTokensResource)
  forward("/api/sys_storage_user_quotas", to: DeeperHub.WebInterface.Resources.SysStorageUserQuotasResource)
  forward("/api/sys_transcoder_audio_files", to: DeeperHub.WebInterface.Resources.SysTranscoderAudioFilesResource)
  forward("/api/sys_transcoder_filters", to: DeeperHub.WebInterface.Resources.SysTranscoderFiltersResource)
  forward("/api/sys_transcoder_images_files", to: DeeperHub.WebInterface.Resources.SysTranscoderImagesFilesResource)
  forward("/api/sys_transcoder_queue", to: DeeperHub.WebInterface.Resources.SysTranscoderQueueResource)
  forward("/api/sys_transcoder_queue_files", to: DeeperHub.WebInterface.Resources.SysTranscoderQueueFilesResource)
  forward("/api/sys_transcoder_videos_files", to: DeeperHub.WebInterface.Resources.SysTranscoderVideosFilesResource)
  forward("/api/sys_wiki_files", to: DeeperHub.WebInterface.Resources.SysWikiFilesResource)
  forward("/api/sys_wiki_images_resized", to: DeeperHub.WebInterface.Resources.SysWikiImagesResizedResource)

  
  forward("/api/terminal", to: DeeperHub.WebInterface.Resources.TerminalResource)
  forward("/api/console", to: DeeperHub.WebInterface.Resources.ConsoleResource)

  # Rota principal para verificação da API
  get "/" do
    conn
    |> put_resp_content_type("application/json")
    |> send_resp(200, Jason.encode!(%{status: "ok", api: "DeeperHub API v1"}))
  end

  # Fallback para rotas não encontradas
  match _ do
    conn
    |> put_resp_content_type("application/json")
    |> send_resp(404, Jason.encode!(%{erro: "Rota não encontrada"}))
  end

  # Log de erros
  def handle_errors(conn, %{kind: kind, reason: reason, stack: stack}) do
    IO.puts("Erro na API: #{inspect(kind)} - #{inspect(reason)}")
    IO.puts("Stack: #{inspect(stack)}")
    send_resp(conn, conn.status || 500, "Erro interno do servidor")
  end
end
