python seeds.py --nodeletefolder --table sys_content_info_grids
python seeds.py --nodeletefolder --table sys_form_displays
python seeds.py --nodeletefolder --table sys_form_display_inputs
python seeds.py --nodeletefolder --table sys_form_inputs
python seeds.py --nodeletefolder --table sys_grid_actions
python seeds.py --nodeletefolder --table sys_grid_fields
python seeds.py --nodeletefolder --table sys_menu_items
python seeds.py --nodeletefolder --table sys_menu_sets
python seeds.py --nodeletefolder --table sys_menu_templates
python seeds.py --nodeletefolder --table sys_objects_content_info
python seeds.py --nodeletefolder --table sys_objects_form
python seeds.py --nodeletefolder --table sys_objects_grid
python seeds.py --nodeletefolder --table sys_objects_menu
python seeds.py --nodeletefolder --table sys_objects_page
python seeds.py --nodeletefolder --table sys_objects_view
python seeds.py --nodeletefolder --table sys_pages_blocks
python seeds.py --nodeletefolder --table sys_pages_blocks_data
python seeds.py --nodeletefolder --table sys_pages_content_placeholders
python seeds.py --nodeletefolder --table sys_pages_layouts
python seeds.py --nodeletefolder --table sys_pages_types
python seeds.py --nodeletefolder --table sys_pages_wiki_blocks
python seeds.py --nodeletefolder --table sys_permalinks
python seeds.py --nodeletefolder --table sys_rewrite_rules
python seeds.py --nodeletefolder --table sys_seo_links
python seeds.py --nodeletefolder --table sys_seo_uri_rewrites
python seeds.py --nodeletefolder --table sys_std_pages
python seeds.py --nodeletefolder --table sys_std_pages_widgets
python seeds.py --nodeletefolder --table sys_std_widgets
python seeds.py --nodeletefolder --table sys_std_widgets_bookmarks