defmodule DeeperHub.Core.Data.Schemas.SysStdWidgetsBookmarks do
  @moduledoc """
  Represents the schema for the 'sys_std_widgets_bookmarks' table.
  This module uses DeeperHub.Core.Data.SchemaBase to provide CRUD operations.
  """
  use DeeperHub.Core.Data.SchemaBase, table_name: "sys_std_widgets_bookmarks"

  # Example Ecto.Schema (optional):
  # use Ecto.Schema
  # import Ecto.Changeset
  #
  # @primary_key {:id, :id, autogenerate: true} # Assuming 'id' is the primary key and autogenerated.
  # schema "sys_std_widgets_bookmarks" do
  #   field :widget_id, :integer
  #   field :profile_id, :integer
  #   field :bookmark, :integer # Corresponds to tinyint(4)
  #
  #   # timestamps() # No timestamp columns in the provided DDL
  # end
  #
  # def changeset(struct_or_schema, attrs) do
  #   # struct_or_schema
  #   # |> cast(attrs, [:widget_id, :profile_id, :bookmark])
  #   # |> validate_required([:widget_id, :profile_id, :bookmark]) # Based on NOT NULL constraints
  #   {struct_or_schema, attrs}
  # end
end
